<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="managememes.aspx.cs" Inherits="MemeMosaic1.managememes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="login" style="height:auto;">
        <center>
        <h1>Delete Memes</h1>
        <hr />
            <br /><br />
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="category" HeaderText="category" SortExpression="category" />
                <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
                <asp:BoundField DataField="disc" HeaderText="disc" SortExpression="disc" />
                <asp:BoundField DataField="dt" HeaderText="dt" SortExpression="dt" />
                <asp:BoundField DataField="img" HeaderText="img" SortExpression="img" />
                <asp:BoundField DataField="added_by" HeaderText="added_by" SortExpression="added_by" />
                <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
            </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [memes]" DeleteCommand="delete from memes where [Id]=@Id"></asp:SqlDataSource>
            <br /><br />
            </center>
         <br /><br />
    </div>

</asp:Content>
